var hierarchy =
[
    [ "matplotlibcpp::detail::_interpreter", "structmatplotlibcpp_1_1detail_1_1__interpreter.html", null ],
    [ "acAnalysisBCInfo", "structacAnalysisBCInfo.html", null ],
    [ "AcAutotuneMeasurement", "structAcAutotuneMeasurement.html", null ],
    [ "AcBuffer", "structAcBuffer.html", null ],
    [ "AcCommunicator", "structAcCommunicator.html", null ],
    [ "AcCompInfo", "structAcCompInfo.html", null ],
    [ "AcCompInfoConfig", "structAcCompInfoConfig.html", null ],
    [ "AcCompInfoHasDefaultValue", "structAcCompInfoHasDefaultValue.html", null ],
    [ "AcCompInfoLoaded", "structAcCompInfoLoaded.html", null ],
    [ "AcComplex", "structAcComplex.html", null ],
    [ "AcComplexInAndOut", "structAcComplexInAndOut.html", null ],
    [ "AcDecompositionInfo", "structAcDecompositionInfo.html", null ],
    [ "AcDeviceKernelOutput", "structAcDeviceKernelOutput.html", null ],
    [ "AcDeviceTmpBuffer", "structAcDeviceTmpBuffer.html", null ],
    [ "AcDimProducts", "structAcDimProducts.html", null ],
    [ "AcDimProductsInv", "structAcDimProductsInv.html", null ],
    [ "AcGridInfo", "structAcGridInfo.html", null ],
    [ "AcGridMappingFunction", "structAcGridMappingFunction.html", null ],
    [ "AcInputs", "structAcInputs.html", null ],
    [ "acm_pack_strategy< T, Allocator >", "classacm__pack__strategy.html", null ],
    [ "acm_pack_strategy_batched< T, Allocator >", "classacm__pack__strategy__batched.html", null ],
    [ "acm_pack_strategy_grouped< T, Allocator >", "classacm__pack__strategy__grouped.html", null ],
    [ "acm_pack_strategy_grouped_batched< T, Allocator >", "classacm__pack__strategy__grouped__batched.html", null ],
    [ "acm_pack_strategy_packed< T, Allocator >", "classacm__pack__strategy__packed.html", null ],
    [ "acm_pack_strategy_packed_batched< T, Allocator >", "classacm__pack__strategy__packed__batched.html", null ],
    [ "AcMatrix", "structAcMatrix.html", null ],
    [ "AcMesh", "structAcMesh.html", null ],
    [ "AcMeshDims", "structAcMeshDims.html", null ],
    [ "AcMeshInfo", "structAcMeshInfo.html", null ],
    [ "AcMeshInfoLoaded", "structAcMeshInfoLoaded.html", null ],
    [ "AcMeshInfoScalars", "structAcMeshInfoScalars.html", null ],
    [ "AcReal3", "structAcReal3.html", null ],
    [ "AcReduceBuffer", "structAcReduceBuffer.html", null ],
    [ "AcReduction", "structAcReduction.html", null ],
    [ "AcScratchpadStates", "structAcScratchpadStates.html", null ],
    [ "AcShape", "structAcShape.html", null ],
    [ "AcShearInterpolationCoeffs", "structAcShearInterpolationCoeffs.html", null ],
    [ "AcTaskGraph", "structAcTaskGraph.html", null ],
    [ "AcTensor", "structAcTensor.html", null ],
    [ "allocate_arrays< P >", "structallocate__arrays.html", null ],
    [ "Array< N >", "structArray.html", null ],
    [ "array_info", "structarray__info.html", null ],
    [ "astnode_s", "structastnode__s.html", null ],
    [ "ac::comm::async_halo_exchange_task< T, Allocator >", "classac_1_1comm_1_1async__halo__exchange__task.html", null ],
    [ "ac::io::async_write_task< T, StagingAllocator >", "classac_1_1io_1_1async__write__task.html", null ],
    [ "ac::base_view< T >", "classac_1_1base__view.html", [
      [ "ac::view< T, Allocator >", "classac_1_1view.html", null ]
    ] ],
    [ "ac::io::batched_async_write_task< T, StagingAllocator >", "classac_1_1io_1_1batched__async__write__task.html", null ],
    [ "bc_fields", "structbc__fields.html", null ],
    [ "bool3", "structbool3.html", null ],
    [ "ac::buffer< T, Allocator >", "classac_1_1buffer.html", null ],
    [ "ac::buffer< T >", "classac_1_1buffer.html", null ],
    [ "ac::buffer< T, ac::mr::pinned_host_allocator >", "classac_1_1buffer.html", null ],
    [ "ac::buffer< T, FirstStageResource >", "classac_1_1buffer.html", null ],
    [ "ac::buffer< T, InternalAllocator >", "classac_1_1buffer.html", null ],
    [ "ac::buffer< T, SecondStageResource >", "classac_1_1buffer.html", null ],
    [ "ac::buffer< uint8_t, Allocator >", "classac_1_1buffer.html", null ],
    [ "ac::mpi::buffered_iallreduce< T, InternalAllocator >", "classac_1_1mpi_1_1buffered__iallreduce.html", null ],
    [ "ac::mpi::buffered_isend< T, InternalAllocator >", "classac_1_1mpi_1_1buffered__isend.html", null ],
    [ "BufferExchangeTask< T, FirstStageResource, SecondStageResource >", "classBufferExchangeTask.html", null ],
    [ "ac::mpi::cart_comm", "classac_1_1mpi_1_1cart__comm.html", null ],
    [ "matplotlibcpp::detail::is_callable_impl< true, T >::Check< U, U >", "structmatplotlibcpp_1_1detail_1_1is__callable__impl_3_01true_00_01T_01_4_1_1Check.html", null ],
    [ "CodeGenInput", "structCodeGenInput.html", null ],
    [ "combinatorial_params", "structcombinatorial__params.html", null ],
    [ "combinatorial_params_info", "structcombinatorial__params__info.html", null ],
    [ "ac::mpi::comm", "classac_1_1mpi_1_1comm.html", null ],
    [ "complex", "structcomplex.html", null ],
    [ "CrossProductInputs", "structCrossProductInputs.html", null ],
    [ "CustomArguments", "structCustomArguments.html", null ],
    [ "ac::mpi::datatype", "classac_1_1mpi_1_1datatype.html", null ],
    [ "device_s", "structdevice__s.html", null ],
    [ "DeviceConfiguration", "structDeviceConfiguration.html", null ],
    [ "DeviceVertexBufferArray", "structDeviceVertexBufferArray.html", null ],
    [ "dfunc_possibilities", "structdfunc__possibilities.html", null ],
    [ "Error", "structError.html", null ],
    [ "matplotlibcpp::detail::is_callable_impl< true, T >::Fallback", "structmatplotlibcpp_1_1detail_1_1is__callable__impl_3_01true_00_01T_01_4_1_1Fallback.html", [
      [ "matplotlibcpp::detail::is_callable_impl< true, T >::Derived", "structmatplotlibcpp_1_1detail_1_1is__callable__impl_3_01true_00_01T_01_4_1_1Derived.html", null ]
    ] ],
    [ "Field2", "structField2.html", null ],
    [ "Field3", "structField3.html", null ],
    [ "Field4", "structField4.html", null ],
    [ "FieldSymmetricTensor", "structFieldSymmetricTensor.html", null ],
    [ "ForcingParams", "structForcingParams.html", null ],
    [ "free_arrays< P >", "structfree__arrays.html", null ],
    [ "func_params_info", "structfunc__params__info.html", null ],
    [ "funcs_calling_info", "structfuncs__calling__info.html", null ],
    [ "ac::future< T >", "classac_1_1future.html", null ],
    [ "gen_constexpr_params", "structgen__constexpr__params.html", null ],
    [ "GpuVtxBufHandles", "structGpuVtxBufHandles.html", null ],
    [ "GridDims", "structGridDims.html", null ],
    [ "ac::mpi::decoupled::halo_exchange< T, Allocator >", "classac_1_1mpi_1_1decoupled_1_1halo__exchange.html", null ],
    [ "ac::mpi::halo_exchange< T, Allocator >", "classac_1_1mpi_1_1halo__exchange.html", null ],
    [ "ac::mpi::hindexed::halo_exchange< T, Allocator >", "classac_1_1mpi_1_1hindexed_1_1halo__exchange.html", null ],
    [ "acm::halo_exchange< T, Allocator >", "classacm_1_1halo__exchange.html", null ],
    [ "acm::rev::halo_exchange< T, Allocator >", "classacm_1_1rev_1_1halo__exchange.html", null ],
    [ "ac::mpi::halo_exchange_batched< T, Allocator >", "classac_1_1mpi_1_1halo__exchange__batched.html", null ],
    [ "HaloMessage", "structHaloMessage.html", null ],
    [ "HaloMessageSwapChain", "structHaloMessageSwapChain.html", null ],
    [ "hashmap_create_options_s", "structhashmap__create__options__s.html", null ],
    [ "hashmap_element_s", "structhashmap__element__s.html", null ],
    [ "hashmap_s", "structhashmap__s.html", null ],
    [ "ac::mpi::hindexed_block< T >", "classac_1_1mpi_1_1hindexed__block.html", null ],
    [ "ac::mr::host_allocator", "structac_1_1mr_1_1host__allocator.html", null ],
    [ "ac::fmt::human_readable", "structac_1_1fmt_1_1human__readable.html", null ],
    [ "in_and_out_indexes", "structin__and__out__indexes.html", null ],
    [ "int3", "structint3.html", null ],
    [ "Int3Hash", "structInt3Hash.html", null ],
    [ "int_vec", "structint__vec.html", null ],
    [ "matplotlibcpp::detail::is_callable< T >", "structmatplotlibcpp_1_1detail_1_1is__callable.html", null ],
    [ "matplotlibcpp::detail::is_callable_impl< obj, T >", "structmatplotlibcpp_1_1detail_1_1is__callable__impl.html", null ],
    [ "matplotlibcpp::detail::is_callable_impl< false, T >", "structmatplotlibcpp_1_1detail_1_1is__callable__impl_3_01false_00_01T_01_4.html", null ],
    [ "matplotlibcpp::detail::is_callable_impl< true, T >", "structmatplotlibcpp_1_1detail_1_1is__callable__impl_3_01true_00_01T_01_4.html", null ],
    [ "KernelAnalysisInfo", "structKernelAnalysisInfo.html", null ],
    [ "KernelConfig", "structKernelConfig.html", null ],
    [ "KernelParameters", "structKernelParameters.html", null ],
    [ "KernelReduceOutput", "structKernelReduceOutput.html", null ],
    [ "KeyEqual", "structKeyEqual.html", null ],
    [ "KeyHash", "structKeyHash.html", null ],
    [ "kiss_fft_cpx", "structkiss__fft__cpx.html", null ],
    [ "kiss_fft_state", "structkiss__fft__state.html", null ],
    [ "kiss_fftnd_state", "structkiss__fftnd__state.html", null ],
    [ "load_all_arrays_uniform< P >", "structload__all__arrays__uniform.html", null ],
    [ "load_all_scalars_uniform< P >", "structload__all__scalars__uniform.html", null ],
    [ "load_arrays< P >", "structload__arrays.html", null ],
    [ "load_comp_arrays< P >", "structload__comp__arrays.html", null ],
    [ "load_comp_scalars< P >", "structload__comp__scalars.html", null ],
    [ "load_scalars< P >", "structload__scalars.html", null ],
    [ "LoadKernelParamsFunc", "structLoadKernelParamsFunc.html", null ],
    [ "ac::fmt::lossless", "structac_1_1fmt_1_1lossless.html", null ],
    [ "mpi_pack_strategy< T, Allocator >", "classmpi__pack__strategy.html", null ],
    [ "mpi_pack_strategy_batched< T, Allocator >", "classmpi__pack__strategy__batched.html", null ],
    [ "mpi_pack_strategy_hindexed< T, Allocator >", "classmpi__pack__strategy__hindexed.html", null ],
    [ "mpi_pack_strategy_hindexed_batched< T, Allocator >", "classmpi__pack__strategy__hindexed__batched.html", null ],
    [ "mpi_pack_strategy_packed< T, Allocator >", "classmpi__pack__strategy__packed.html", null ],
    [ "ac::ndbuffer< T, Allocator >", "structac_1_1ndbuffer.html", null ],
    [ "node_s", "structnode__s.html", null ],
    [ "node_vec", "structnode__vec.html", null ],
    [ "ac::ntuple< T >", "classac_1_1ntuple.html", null ],
    [ "ac::ntuple< uint64_t >", "classac_1_1ntuple.html", null ],
    [ "op_vec", "structop__vec.html", null ],
    [ "overloaded_dfuncs", "structoverloaded__dfuncs.html", null ],
    [ "ac::comm::packet< T, Allocator >", "classac_1_1comm_1_1packet.html", null ],
    [ "ac::mpi::decoupled::packet< T, Allocator >", "classac_1_1mpi_1_1decoupled_1_1packet.html", null ],
    [ "ac::mpi::hindexed::packet< T, Allocator >", "classac_1_1mpi_1_1hindexed_1_1packet.html", null ],
    [ "ac::mpi::packet< T, Allocator >", "classac_1_1mpi_1_1packet.html", null ],
    [ "acm::packet< T, Allocator >", "classacm_1_1packet.html", null ],
    [ "acm::rev::packet< T, Allocator >", "classacm_1_1rev_1_1packet.html", null ],
    [ "param_combinations", "structparam__combinations.html", null ],
    [ "matplotlibcpp::Plot", "classmatplotlibcpp_1_1Plot.html", null ],
    [ "matplotlibcpp::detail::plot_impl< IsYDataCallable >", "structmatplotlibcpp_1_1detail_1_1plot__impl.html", null ],
    [ "matplotlibcpp::detail::plot_impl< std::false_type >", "structmatplotlibcpp_1_1detail_1_1plot__impl_3_01std_1_1false__type_01_4.html", null ],
    [ "matplotlibcpp::detail::plot_impl< std::true_type >", "structmatplotlibcpp_1_1detail_1_1plot__impl_3_01std_1_1true__type_01_4.html", null ],
    [ "ProfileBufferArray", "structProfileBufferArray.html", null ],
    [ "ProfileZ3", "structProfileZ3.html", null ],
    [ "real2", "structreal2.html", null ],
    [ "real3", "structreal3.html", null ],
    [ "real4", "structreal4.html", null ],
    [ "real5", "structreal5.html", null ],
    [ "real_symmetric_tensor", "structreal__symmetric__tensor.html", null ],
    [ "Region", "structRegion.html", null ],
    [ "RegionMemory", "structRegionMemory.html", null ],
    [ "RegionMemoryInputParams", "structRegionMemoryInputParams.html", null ],
    [ "ac::mpi::request", "classac_1_1mpi_1_1request.html", null ],
    [ "ac::segment", "structac_1_1segment.html", null ],
    [ "size_t2", "structsize__t2.html", null ],
    [ "size_t2Hash", "structsize__t2Hash.html", null ],
    [ "sld_fluxes", "structsld__fluxes.html", null ],
    [ "SOAVector", "structSOAVector.html", null ],
    [ "state", "structstate.html", null ],
    [ "ac::static_ntuple< T, N >", "classac_1_1static__ntuple.html", null ],
    [ "string_vec", "structstring__vec.html", null ],
    [ "structs_info", "structstructs__info.html", null ],
    [ "ac::mpi::subarray< T >", "classac_1_1mpi_1_1subarray.html", null ],
    [ "Symbol", "structSymbol.html", null ],
    [ "T", null, [
      [ "matplotlibcpp::detail::is_callable_impl< true, T >::Derived", "structmatplotlibcpp_1_1detail_1_1is__callable__impl_3_01true_00_01T_01_4_1_1Derived.html", null ]
    ] ],
    [ "Task", "classTask.html", [
      [ "BoundaryConditionTask", "classBoundaryConditionTask.html", null ],
      [ "ComputeTask", "classComputeTask.html", null ],
      [ "HaloExchangeTask", "classHaloExchangeTask.html", null ],
      [ "MPIScanTask", "classMPIScanTask.html", null ],
      [ "ReduceTask< T >", "classReduceTask.html", null ]
    ] ],
    [ "TBConfig", "structTBConfig.html", null ],
    [ "te_expr", "structte__expr.html", null ],
    [ "te_variable", "structte__variable.html", null ],
    [ "ac::timer", "classac_1_1timer.html", null ],
    [ "ac::timewriter", "classac_1_1timewriter.html", null ],
    [ "TraceFile", "structTraceFile.html", null ],
    [ "traverse_base_params", "structtraverse__base__params.html", null ],
    [ "tspecifier", "structtspecifier.html", null ],
    [ "ac::mpi::twoway_buffered_iallreduce< T, InternalAllocator >", "classac_1_1mpi_1_1twoway__buffered__iallreduce.html", null ],
    [ "uint2_64", "structuint2__64.html", null ],
    [ "uint3_64", "structuint3__64.html", null ],
    [ "update_arrays< P >", "structupdate__arrays.html", null ],
    [ "user_enums_info", "structuser__enums__info.html", null ],
    [ "variable", "structvariable.html", null ],
    [ "VecZProfile", "structVecZProfile.html", null ],
    [ "VertexBufferArray", "structVertexBufferArray.html", null ],
    [ "Volume", "structVolume.html", null ],
    [ "VolumeHash", "structVolumeHash.html", null ]
];